### PR TITLE
Update bot.py

### PR DESCRIPTION
**Pull request by HexyeDEV**
Automatically load every cog instead of running the command

### CODE REVIEW

**Comment by R2Boyo25** [comment]
It already does. On line 393 to the end of the file.
-- 
Ohin T.

**Comment by kazani-dev** [comment]
It already does load every extension, lines 386 to 412.

If you’re saying that git isn’t getting loaded then remove it from disabled.txt

**Comment by HexyeDEV** [comment]
No,  I'm saying that instead of using the cmd you could just use that

**Comment by HexyeDEV** [comment]
I changed the wrong part in the commit, instead of changing the load command i changes the unload but that was what i ment

**Comment by kazani-dev** [comment]
It already loads every extension, the commands are in case you want to unload / load / reload an extension while the bot is running, after the initial loading in the `if __name__ == "__main__":` statement

**Comment by HexyeDEV** [comment]
Let me do it better, i'll make another pull

**Pull request closed without merging**
